### ISSUE TITLE
Project Presentation

### ISSUE THREAD

**Issue by Bibbleboop** [SeanMH8911/Music-Genie#3]
Still to discuss..

**Comment by Bibbleboop** [comment]
- [ ] Write a one minute description of application - is this in addition to the power point slides or instead of 

- [ ] 

- [ ]

**Comment by Syed-Jaffery** [comment]
Project Presentation Template


1. Elevator pitch: a one minute description of your application

2. Concept: What is your user story? What was your motivation for development?

3. Process: What were the technologies used? How were tasks and roles broken down and assigned? What challenges did you encounter? What were your successes?

4. Demo: Show your stuff! (Using loom recording of around 2 mins)

5. Directions for Future Development

6. Links to the deployed application and the GitHub repository
